data:
  # CSV for path and metadata to training examples. for bidner data collect but not training
  dataset:
    seed: 123
    cut_mode: False
    cut_length: 1000
    max_num_res: 5000
    resolution: 3.
    chains: all
    category:
    complex: 1
    use_cluster: False

    cache_num_res: 0
    min_num_res: 40
    subset: null
    samples_per_eval_length: 5
    num_eval_lengths: 10
    min_eval_length: 512
    csv_path: //home/junyu/project/binder_target/1bj1/preprocessed/metadata.csv
    pkl_file_path:

  loader:
    num_workers: 32
    prefetch_factor: 10
  sampler:
    max_batch_size: 10
    max_num_res_squared: 250000
